stages:
  data_collection:
    cmd: python src/data/data_collection.py
    deps:
    - WA_Fn-UseC_-Telco-Customer-Churn.csv
    - src/data/data_collection.py
    outs:
    - data/raw
  data_prep:
    cmd: python src/data/data_prep.py
    deps:
    - data/raw/cleaned_telco_churn.csv
    - src/data/data_prep.py
    outs:
    - data/interim
  data_split:
    cmd: python src/data/data_split.py
    deps:
    - data/interim
    - src/data/data_split.py
    outs:
    - data/processed
  model_building:
    cmd: python src/model/model_building.py
    deps:
    - src/model/model_building.py
    - ./data/processed
    params:
    - train
    metrics:
      - reports:
          cache: false
  model_eval_reg:
    cmd: python src/model/model_eval_reg.py
    deps:
    - src/model
    - ./data/processed
  model_staging:
    cmd: python src/model/model_staging.py
    deps:
    - reports/run_info.json
    - src/model/model_staging.py
    

    
