name: CI pipeline

on: push

jobs:
  project-testing:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout code
         uses: actions/checkout@v3

       - name: Setup Python
         uses: actions/setup-python@v4
         with:
           python-version: '3.12.11'

       - name: Install dependencies
         run: |
           pip isntall --upgrade pip
           pip install -r requirements.txt
           pip install dvc

       - name: Run DVC pipeline
         env:
           DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN}}
         run: |
           dvc repro
      #  - name: Promote model to production
      #    if: success()
      #    env: 
      #      DAGSHUB_TOKEN: ${{ secrets.DAGSHUB_TOKEN}}
      #    run: python scripts/production.py

      #    # Log in to Dockerhub
      #  - name: Log in to DockerHub
      #    uses: docker/login-action@v2
      #    with:
      #      username: ${{ secrets.DOCKER_USERNAME }}
      #      password: ${{ secrets.DOCKER_TOKEN}}

      #    # Build Docker Image
      #  - name: Build Docker Image
      #    if: ${{ successs()}}
      #    run: |
      #     docker build -t anshu57/telecom-customer-churn-prediction:latest .
